export const products = [
    {
        id : 'sadf1234',
        name: 'Product 1',
        image : 'image1.jpg',
        description: 'Description for Product 1',
        price: 100,
        quantity: 10,
        category: 'Category A',
        onStock: true,
    },
    {
        id : 'sadf1235',
        name: 'Product 2',
        image : 'image2.jpg',
        description: 'Description for Product 2',
        price: 200,
        quantity: 5,
        category: 'Category B',
        onStock: false,
    },
    {
        id : 'sadf1236',
        name: 'Product 3',
        image : 'image3.jpg',
        description: 'Description for Product 3',
        price: 300,
        quantity: 0,
        category: 'Category C',
        onStock: false,
    },
    {
        id : 'sadf1237',
        name: 'Product 4',
        image : 'image4.jpg',
        description: 'Description for Product 4',
        price: 400,
        quantity: 8,
        category: 'Category D',
        onStock: true,
    },
    {
        id : 'sadf1238',
        name: 'Product 5',
        image : 'image5.jpg',
        description: 'Description for Product 5',
        price: 500,
        quantity: 12,
        category: 'Category E',
        onStock: true,
    }
]